#!/usr/bin/env bash
# Re-verify our layout assumptions against PUBLISHED artifacts rather than the
# upstream default branch. See ../DECISIONS.md ADR-0004 — we got this wrong once.
#
# Prints the crate inventory to stdout AND regenerates docs/upstream-crates.md, so
# the check leaves a dated artifact in the repository rather than only a scrollback
# buffer. That file is generated: edit this script, not the output.
set -euo pipefail

CRATES=(surrealdb-kvs surrealdb-kvs-any surrealdb-kvs-rocksdb surrealdb-kvs-surrealkv \
        surrealdb-kvs-mem surrealdb-kvs-tikv surrealdb-kvs-test \
        surrealdb-engine-api surrealdb-engine-local surrealdb-datastore \
        surrealdb-catalog surrealdb-node surrealdb-cnf surrealdb-server surrealdb)

OUT="docs/upstream-crates.md"
mkdir -p "$(dirname "$OUT")"
REPORT="$(mktemp)"
trap 'rm -f "$REPORT"' EXIT

printf '%-28s %-12s %s\n' CRATE VERSION LICENSE > "$REPORT"
printf '%-28s %-12s %s\n' '----' '-------' '-------' >> "$REPORT"
for c in "${CRATES[@]}"; do
  out=$(curl -s -H 'User-Agent: open-surrealdb-ds-audit' "https://crates.io/api/v1/crates/$c")
  read -r ver lic <<<"$(printf '%s' "$out" | python3 -c '
import sys, json
try:
    d = json.load(sys.stdin)
    if "crate" in d:
        c = d["crate"]
        ver = c.get("max_stable_version") or c.get("max_version") or "-"
        # The licence lives on the version, not the crate, for BUSL crates
        # (which publish with license = "non-standard" and a license-file).
        lic = "-"
        for v in d.get("versions", []):
            if v.get("num") == ver or v.get("yanked") is False:
                lic = v.get("license") or "-"
                if lic != "-":
                    break
        if lic == "-":
            lic = c.get("license") or "-"
        print(ver, lic)
    else:
        print("absent", "-")
except Exception:
    print("error", "-")
')"
  printf '%-28s %-12s %s\n' "$c" "$ver" "$lic" >> "$REPORT"
done

{
  echo "# Upstream crate inventory"
  echo
  echo "<!-- GENERATED by scripts/audit-upstream.sh — do not edit. -->"
  echo
  echo "Checked against crates.io on $(date -u +%Y-%m-%d)."
  echo
  echo '```'
  cat "$REPORT"
  echo '```'
} > "$OUT"

cat "$REPORT"

cat <<'NOTE'

Expectations to re-check when this output changes:

  * `license = non-standard` means BUSL-1.1. If any crate reports Apache-2.0 or
    MIT, ADR-0002's Path A cost drops — re-evaluate.
  * A crate appearing that we don't depend on may mean a layout change.
  * `surrealdb-kvs-test` and `surrealdb-node` are expected to be ABSENT from
    crates.io (publish = false). They must come from the vendored tree.

The upstream default branch is NOT the release. Pin the tag. See ADR-0001.

Wrote docs/upstream-crates.md.
NOTE
